CTUPAD.Web/CTUPAD.Web/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CTUPAD.Web.Data;
using CTUPAD.Web.Models.CustomModel;
using Microsoft.AspNetCore.Authorization;

namespace CTUPAD.Web.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryID,CategoryName")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryID,CategoryName")] Category category)
        {
            if (id != category.CategoryID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.CategoryID == id);
        }
    }
}

CTUPAD.Web/CTUPAD.Web/Controllers/CategoryCriteariasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using CTUPAD.Web.Data;
using CTUPAD.Web.Models.CustomModel;
using Microsoft.AspNetCore.Authorization;

namespace CTUPAD.Web.Controllers
{
    [Authorize]
    public class CategoryCriteariasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoryCriteariasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CategoryCritearias
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.CategoryCritearias.Include(c => c.Category);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: CategoryCritearias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoryCritearia = await _context.CategoryCritearias
                .Include(c => c.Category)
                .FirstOrDefaultAsync(m => m.CategoryCriteariaID == id);
            if (categoryCritearia == null)
            {
                return NotFound();
            }

            return View(categoryCritearia);
        }

        // GET: CategoryCritearias/Create
        public IActionResult Create()
        {
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName");
            return View();
        }

        // POST: CategoryCritearias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryCriteariaID,CategoryID,CategoryCriteariaName")] CategoryCritearia categoryCritearia)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categoryCritearia);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", categoryCritearia.CategoryID);
            return View(categoryCritearia);
        }

        // GET: CategoryCritearias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoryCritearia = await _context.CategoryCritearias.FindAsync(id);
            if (categoryCritearia == null)
            {
                return NotFound();
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", categoryCritearia.CategoryID);
            return View(categoryCritearia);
        }

        // POST: CategoryCritearias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryCriteariaID,CategoryID,CategoryCriteariaName")] CategoryCritearia categoryCritearia)
        {
            if (id != categoryCritearia.CategoryCriteariaID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoryCritearia);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryCriteariaExists(categoryCritearia.CategoryCriteariaID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", categoryCritearia.CategoryID);
            return View(categoryCritearia);
        }

        // GET: CategoryCritearias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoryCritearia = await _context.CategoryCritearias
                .Include(c => c.Category)
                .FirstOrDefaultAsync(m => m.CategoryCriteariaID == id);
            if (categoryCritearia == null)
            {
                return NotFound();
            }

            return View(categoryCritearia);
        }

        // POST: CategoryCritearias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var categoryCritearia = await _context.CategoryCritearias.FindAsync(id);
            _context.CategoryCritearias.Remove(categoryCritearia);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryCriteariaExists(int id)
        {
            return _context.CategoryCritearias.Any(e => e.CategoryCriteariaID == id);
        }
    }
}

CTUPAD.Web/CTUPAD.Web/Controllers/ContestantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using CTUPAD.Web.Data;
using CTUPAD.Web.Models.CustomModel;
using Microsoft.AspNetCore.Authorization;

namespace CTUPAD.Web.Controllers
{
    [Authorize]
    public class ContestantsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContestantsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Contestants
        public async Task<IActionResult> Index()
        {
            return View(await _context.Contestants.ToListAsync());
        }

        // GET: Contestants/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contestant = await _context.Contestants
                .FirstOrDefaultAsync(m => m.ContestantID == id);
            if (contestant == null)
            {
                return NotFound();
            }

            return View(contestant);
        }

        // GET: Contestants/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contestants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ContestantID,ContestantFirstName,ContestantLastName")] Contestant contestant)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contestant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(contestant);
        }

        // GET: Contestants/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contestant = await _context.Contestants.FindAsync(id);
            if (contestant == null)
            {
                return NotFound();
            }
            return View(contestant);
        }

        // POST: Contestants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ContestantID,ContestantFirstName,ContestantLastName")] Contestant contestant)
        {
            if (id != contestant.ContestantID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contestant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContestantExists(contestant.ContestantID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contestant);
        }

        // GET: Contestants/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contestant = await _context.Contestants
                .FirstOrDefaultAsync(m => m.ContestantID == id);
            if (contestant == null)
            {
                return NotFound();
            }

            return View(contestant);
        }

        // POST: Contestants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contestant = await _context.Contestants.FindAsync(id);
            _context.Contestants.Remove(contestant);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContestantExists(int id)
        {
            return _context.Contestants.Any(e => e.ContestantID == id);
        }
    }
}

CTUPAD.Web/CTUPAD.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Setup</h1>
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <a type="button" class="btn btn-primary form-control m-1 p-1" asp-action="Index" asp-controller="Contestants">Edit Contestant</a>
            <a type="button" class="btn btn-primary form-control m-1 p-1" asp-action="Index" asp-controller="Categories">Edit Category</a>
            <a type="button" class="btn btn-primary form-control m-1 p-1" asp-action="Index" asp-controller="CategoryCritearias">Edit Criteria</a>
        </div>
        <div class="col-4"></div>
    </div>
    
</div>

CTUPAD.Web/CTUPAD.Web/Views/Home/JudgePage.cshtml
@model JugdeEvaluationViewModel

@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "JudgePage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-4">
        <h1>Category</h1>
        <hr />
        <div class="CategoriesToRate">
            @{
                foreach (Category cat in Model.ListOfCategories)
                {
                    <button type="button" class="btn btn-block btn-primary" onclick="setSelectedCategory(@cat.CategoryID, '@cat.CategoryName');">@cat.CategoryName</button>
                }
            }



        </div>

    </div>
    <div class="col-8">
        <h1>Rate Contestants</h1>
        <hr />
        <h4>Selected Category - <span id="spanCurrentlySelectedCategory">None</span></h4>
        <hr />
        <strong>Select Contestant Name</strong><br />
        <select asp-for="ContestantID" asp-items="Model.Contestants" class="select2_Contestants form-control"></select>

        <hr />

        <div id="divCategoryCriteria">
            <div class="form-group">
                <label></label>
                <input class="touchspin1" type="text" value="0" name="demo1">

            </div>

        </div>
        <button type="button" class="btn btn-primary form-control mt-5  " onclick="SaveContestantRatings();">Add/Update Scores</button>
    </div>
</div>
@Html.HiddenFor(x => x.JudgeID)
@section Styles {

    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
        <link rel="stylesheet" href="~/lib/select2/dist/css/select2.min.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.css" />

    </environment>
}

@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/lib/select2/dist/js/select2.min.js"></script>
        <script src="~/lib/toastr/toastr.min.js"></script>
        <script src="~/lib/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js"></script>
    </environment>

    <script type="text/javascript">

        //Main CriteriaData
            /*

[{
CategoryCriteariaID = 0,
        Rating = 0
}]

*/
    var MAIN_CRITERIA_DATA = new Array();
        //Global Variables
    var SELECTED_CATEGORYID = 0;

    var objdivCategoryCriteria;
    var cboObjContestants;
    var objspanCurrentlySelectedCategory;

    function setSelectedCategory(aCategoryID,aCategoryName) {
        SELECTED_CATEGORYID = aCategoryID;
       // alert(cboObjContestants.val());
        objspanCurrentlySelectedCategory.html(aCategoryName);
        LoadCategoryCriteria();
    }
    function SaveContestantRatings() {
        var Rtn = new Array();
        $.each(MAIN_CRITERIA_DATA, function (i,item) {
             var _ViewModel = JSON.parse('{}');

            _ViewModel.ContestantID = cboObjContestants.val();
            _ViewModel.JugeID = $("#JudgeID").val();
            _ViewModel.CategoryID = SELECTED_CATEGORYID;
            _ViewModel.CategoryCriteariaID = item.CategoryCriteariaID;
            _ViewModel.Rating = item.Rating;
            Rtn[Rtn.length] = _ViewModel
        });
        

            $.ajax({
                type: "post",
                url: '@Url.Action("SaveCategoryCriteria", "Home")',
                        data: JSON.stringify(Rtn),
                        contentType: "application/json; charset=utf-8",
                        beforeSend: function (xhr) {
                        xhr.setRequestHeader("RequestVerificationToken",
                            $('input:hidden[name="__RequestVerificationToken"]').val());
                    },
                dataType: "json",
                success: function (data) {
                    //clearCategoryCriteria();
                    //populateHardSkillSelect(data);
                    //BuildCategoryCritearia(data);
                    toastr.success('Criteria Saved', 'Success');
                },
                    error: function (data, textStatus, error) {
                        toastr.error("Something went wrong - " + error, 'Error');
                }
            });
    }
    function LoadCategoryCriteria() {


        if (cboObjContestants.val() == null) {
            objdivCategoryCriteria.html('Please Select Contest!');
        }
        if (SELECTED_CATEGORYID == 0) {
            objdivCategoryCriteria.html('Please Select Category!');
        }
        if ((SELECTED_CATEGORYID != 0) && (cboObjContestants.val() != null)) {
             var _ViewModel = JSON.parse('{}');

            _ViewModel.ContestantID = cboObjContestants.val();
            _ViewModel.JugeID = $("#JudgeID").val();
            _ViewModel.CategoryID = SELECTED_CATEGORYID;

            $.ajax({
                type: "post",
                url: '@Url.Action("GetCategoryCriteria", "Home")',
                        data: JSON.stringify(_ViewModel),
                        contentType: "application/json; charset=utf-8",
                        beforeSend: function (xhr) {
                        xhr.setRequestHeader("RequestVerificationToken",
                            $('input:hidden[name="__RequestVerificationToken"]').val());
                    },
                dataType: "json",
                success: function (data) {
                    clearCategoryCriteria();
                    //populateHardSkillSelect(data);
                    BuildCategoryCritearia(data);
                    toastr.success('Criteria Loaded', 'Success');
                },
                    error: function (data, textStatus, error) {
                        toastr.error("Something went wrong - " + error, 'Error');
                }
            });
        }


    }
    function clearCategoryCriteria() {
        objdivCategoryCriteria.html('');
        MAIN_CRITERIA_DATA = new Array();
    }

    function setCriteriaItem(txtObj,categoryCriteariaID ) {
       

        $.each(MAIN_CRITERIA_DATA, function (i,item) {
            if (item.CategoryCriteariaID == categoryCriteariaID) {
                MAIN_CRITERIA_DATA[i].Rating = $(txtObj).val();
            }
        });
        //alert(JSON.stringify(MAIN_CRITERIA_DATA));
    }
    function BuildCategoryCritearia(data) {
        
        var html = '<div class="row">';
        html += '<div class="col-12 mt-2"><table>';
       
        if (data.length > 0) {
            $.each(data, function (i, item) {

            html += '<tr><td><div class="form-group">';
                html += '<label><strong>' + item.categoryCriteariaName + '</strong></label></td>';
                html += '<td><input class="touchspin1" onchange="setCriteriaItem(this,' + item.categoryCriteariaID + ');" type="text" value="' + item.rating + '" name="demo1"></td>';
                html += '</tr></div>';

                var criteriaItem = JSON.parse('{}');
                
                criteriaItem.CategoryCriteariaID = item.categoryCriteariaID;
                criteriaItem.Rating = item.rating;

                MAIN_CRITERIA_DATA[MAIN_CRITERIA_DATA.length] = criteriaItem;
        });
        } else {
            html += '<tr><td><span class="alert alert-warning">No Criteria Setup! PLease Add Criteria.</span></td></tr>';
        }

        html += '</table></div >';
            html += '</div>';
        objdivCategoryCriteria.html(html);
        $(".touchspin1").TouchSpin({
                buttondown_class: 'btn btn-white',
            buttonup_class: 'btn btn-white',
                 min: 0,
                max: 10,
            step: 0.5,
                decimals: 1
        });
        
    }
    $(document).ready(function () {
        objdivCategoryCriteria = $("#divCategoryCriteria");
        objspanCurrentlySelectedCategory = $("#spanCurrentlySelectedCategory");
          cboObjContestants =   $(".select2_Contestants").select2({
                placeholder: "Select a Contestant",
                allowClear: true
            });

        cboObjContestants.change(function () {
                //LoadIndustries($(this).val());
                //setIndustrySelectionSummary();

            clearCategoryCriteria();
            LoadCategoryCriteria();
        });
        cboObjContestants.val(null);
        cboObjContestants.trigger('change');
        toastr.options.progressBar = true;
        toastr.options.preventDuplicates = true;
        toastr.options.newestOnTop = true;
        toastr.options.closeButton = true;
        });

    </script>
}